<a href="https://colab.research.google.com/github/raju98610/Oil-Spill-Dataseta/blob/main/Major_Assignment_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
# pandas is aliased as pd
import numpy as np
# numpy is aliased as np
import matplotlib.pyplot as plt
# pyplot is aliased as plt
import warnings
warnings.simplefilter('ignore')

In [ ]:
oil_spill_dataset = pd.read_csv("oil_spill.csv")
oil_spill_dataset

f_1    f_2      f_3     f_4  f_5       f_6    f_7    f_8      f_9  f_10  \
0      1   2558  1506.09  456.63   90   6395000  40.88   7.89  29780.0  0.19   
1      2  22325    79.11  841.03  180  55812500  51.11   1.21  61900.0  0.02   
2      3    115  1449.85  608.43   88    287500  40.42   7.34   3340.0  0.18   
3      4   1201  1562.53  295.65   66   3002500  42.40   7.97  18030.0  0.19   
4      5    312   950.27  440.86   37    780000  41.43   7.03   3350.0  0.17   
..   ...    ...      ...     ...  ...       ...    ...    ...      ...   ...   
932  200     12    92.42  364.42  135     97200  59.42  10.34    884.0  0.17   
933  201     11    98.82  248.64  159     89100  59.64  10.18    831.0  0.17   
934  202     14    25.14  428.86   24    113400  60.14  17.94    847.0  0.30   
935  203     10    96.00  451.30   68     81000  59.90  15.01    831.0  0.25   
936  204     11     7.73  235.73  135     89100  61.82  12.24    831.0  0.20   

     ...     f_41      f_42     f_43     f_44   f_45  f_46      f_47   f_48  \
0    ...  2850.00   1000.00   763.16   135.46   3.73     0  33243.19  65.74   
1    ...  5750.00  11500.00  9593.48  1648.80   0.60     0  51572.04  65.73   
2    ...  1400.00    250.00   150.00    45.13   9.33     1  31692.84  65.81   
3    ...  6041.52    761.58   453.21   144.97  13.33     1  37696.21  65.67   
4    ...  1320.04    710.63   512.54   109.16   2.58     0  29038.17  65.66   
..   ...      ...       ...      ...      ...    ...   ...       ...    ...   
932  ...   381.84    254.56    84.85   146.97   4.50     0   2593.50  65.85   
933  ...   284.60    180.00   150.00    51.96   1.90     0   4361.25  65.70   
934  ...   402.49    180.00   180.00     0.00   2.24     0   2153.05  65.91   
935  ...   402.49    180.00    90.00    73.48   4.47     0   2421.43  65.97   
936  ...   254.56    254.56   127.28   180.00   2.00     0   3782.68  65.65   

     f_49  target  
0    7.95       1  
1    6.26       0  
2    7.84       1  
3    8.07       1  
4    7.35       0  
..    ...     ...  
932  6.39       0  
933  6.53       0  
934  6.12       0  
935  6.32       0  
936  6.26       0  

[937 rows x 50 columns]

In [ ]:
oil_spill_dataset.shape
# rows=937 ,columns = 50

(937, 50)

In [ ]:
oil_spill_dataset.columns

Index(['f_1', 'f_2', 'f_3', 'f_4', 'f_5', 'f_6', 'f_7', 'f_8', 'f_9', 'f_10',
       'f_11', 'f_12', 'f_13', 'f_14', 'f_15', 'f_16', 'f_17', 'f_18', 'f_19',
       'f_20', 'f_21', 'f_22', 'f_23', 'f_24', 'f_25', 'f_26', 'f_27', 'f_28',
       'f_29', 'f_30', 'f_31', 'f_32', 'f_33', 'f_34', 'f_35', 'f_36', 'f_37',
       'f_38', 'f_39', 'f_40', 'f_41', 'f_42', 'f_43', 'f_44', 'f_45', 'f_46',
       'f_47', 'f_48', 'f_49', 'target'],
      dtype='object')

In [ ]:
oil_spill_dataset.dtypes


f_1         int64
f_2         int64
f_3       float64
f_4       float64
f_5         int64
f_6         int64
f_7       float64
f_8       float64
f_9       float64
f_10      float64
f_11      float64
f_12      float64
f_13      float64
f_14      float64
f_15      float64
f_16      float64
f_17      float64
f_18      float64
f_19      float64
f_20      float64
f_21      float64
f_22      float64
f_23        int64
f_24      float64
f_25      float64
f_26      float64
f_27      float64
f_28      float64
f_29      float64
f_30      float64
f_31      float64
f_32      float64
f_33      float64
f_34      float64
f_35        int64
f_36        int64
f_37      float64
f_38      float64
f_39        int64
f_40        int64
f_41      float64
f_42      float64
f_43      float64
f_44      float64
f_45      float64
f_46        int64
f_47      float64
f_48      float64
f_49      float64
target      int64
dtype: object

In [ ]:
oil_spill_dataset.duplicated().sum()

0

In [ ]:
oil_spill_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 937 entries, 0 to 936
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   f_1     937 non-null    int64  
 1   f_2     937 non-null    int64  
 2   f_3     937 non-null    float64
 3   f_4     937 non-null    float64
 4   f_5     937 non-null    int64  
 5   f_6     937 non-null    int64  
 6   f_7     937 non-null    float64
 7   f_8     937 non-null    float64
 8   f_9     937 non-null    float64
 9   f_10    937 non-null    float64
 10  f_11    937 non-null    float64
 11  f_12    937 non-null    float64
 12  f_13    937 non-null    float64
 13  f_14    937 non-null    float64
 14  f_15    937 non-null    float64
 15  f_16    937 non-null    float64
 16  f_17    937 non-null    float64
 17  f_18    937 non-null    float64
 18  f_19    937 non-null    float64
 19  f_20    937 non-null    float64
 20  f_21    937 non-null    float64
 21  f_22    937 non-null    float64
 22  f_

In [ ]:
oil_spill_dataset.isna().sum()

f_1       0
f_2       0
f_3       0
f_4       0
f_5       0
f_6       0
f_7       0
f_8       0
f_9       0
f_10      0
f_11      0
f_12      0
f_13      0
f_14      0
f_15      0
f_16      0
f_17      0
f_18      0
f_19      0
f_20      0
f_21      0
f_22      0
f_23      0
f_24      0
f_25      0
f_26      0
f_27      0
f_28      0
f_29      0
f_30      0
f_31      0
f_32      0
f_33      0
f_34      0
f_35      0
f_36      0
f_37      0
f_38      0
f_39      0
f_40      0
f_41      0
f_42      0
f_43      0
f_44      0
f_45      0
f_46      0
f_47      0
f_48      0
f_49      0
target    0
dtype: int64

In [ ]:
target_var = oil_spill_dataset["target"].value_counts()
print("Target distribution:")
print(target_var)


Target distribution:
0    896
1     41
Name: target, dtype: int64


#count the target values

In [ ]:
#Prepare the data for modeling
X = oil_spill_dataset.drop("target", axis=1)  # X = oil_spill_dataset.iloc[:,:-1])
y = oil_spill_dataset["target"]               # y = oil_spill_dataset.iloc[:,-1])
print(type(X))  # dataframe
print(type(y))  # series
print(X.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(937, 49)
(937,)


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=22)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(702, 49)
(235, 49)
(702,)
(235,)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

In [ ]:
dt = DecisionTreeClassifier(criterion='gini',max_depth=10,min_samples_split=20)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [ ]:
def cls_eval(ytest,ypred):
    cm = confusion_matrix(ytest,ypred)
    print(cm)
    print('Accuracy Score',accuracy_score(ytest,ypred))
    print(classification_report(ytest,ypred,zero_division=0))

def mscore(model):
    print('Training Score',model.score(x_train,y_train))  # Training accuracy
    print('Testing Score',model.score(x_test,y_test))     # testing accuracy

In [ ]:
print(X.shape)

(937, 49)


In [ ]:
bc_dt = BaggingClassifier(base_estimator=dt,n_estimators=15,
                          max_samples=X.shape[0],max_features=X.shape[1],
                          random_state=2022)
bc_dt.fit(X,y)

BaggingClassifier(base_estimator=DecisionTreeClassifier(max_depth=10,
                                                        min_samples_split=20),
                  max_features=49, max_samples=937, n_estimators=15,
                  random_state=2022)

In [ ]:
mscore(bc_dt)

Training Score 0.9772079772079773
Testing Score 0.9787234042553191


In [ ]:
ypred_bc = bc_dt.predict(x_test)
print(ypred_bc)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
cls_eval(y_test,ypred_bc)

[[225   0]
 [  5   5]]
Accuracy Score 0.9787234042553191
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       225
           1       1.00      0.50      0.67        10

    accuracy                           0.98       235
   macro avg       0.99      0.75      0.83       235
weighted avg       0.98      0.98      0.98       235



In [ ]:
rf = RandomForestClassifier(n_estimators=25,criterion='gini',min_samples_split=20,max_depth=10)
rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=10, min_samples_split=20, n_estimators=25)

In [ ]:
# Training and the testing Score
mscore(rf)

Training Score 0.9700854700854701
Testing Score 0.9531914893617022


In [ ]:
# Generating the predictions
ypred_rf = rf.predict(x_test)

# Generating the predictions

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
#Feature scaling
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
#  Model training and evaluation
# Random Forest Classifier
rf_model = RandomForestClassifier()
rf_model.fit(x_train_scaled, y_train)

RandomForestClassifier()

In [ ]:
rf_predictions = rf_model.predict(x_test_scaled)
print("Random Forest Classifier:")
print(classification_report(y_test, rf_predictions))
print("Accuracy:", accuracy_score(y_test, rf_predictions))
print()

Random Forest Classifier:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       225
           1       1.00      0.20      0.33        10

    accuracy                           0.97       235
   macro avg       0.98      0.60      0.66       235
weighted avg       0.97      0.97      0.95       235

Accuracy: 0.9659574468085106



In [ ]:
from sklearn.ensemble import  AdaBoostClassifier

In [ ]:
tree = DecisionTreeClassifier(random_state=2022,max_depth=3,criterion='entropy',min_samples_split=8)

In [ ]:
ada_boost = AdaBoostClassifier(base_estimator=tree,n_estimators=80)
ada_boost.fit(x_train,y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy',
                                                         max_depth=3,
                                                         min_samples_split=8,
                                                         random_state=2022),
                   n_estimators=80)

In [ ]:
mscore(ada_boost)

Training Score 1.0
Testing Score 0.9659574468085106


In [ ]:
ypred = ada_boost.predict(x_test)
print(len(ypred))
print(ypred)

235
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
cls_eval(y_test,ypred)

[[224   1]
 [  7   3]]
Accuracy Score 0.9659574468085106
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       225
           1       0.75      0.30      0.43        10

    accuracy                           0.97       235
   macro avg       0.86      0.65      0.71       235
weighted avg       0.96      0.97      0.96       235



In [ ]:
print(x_train.shape)
print(x_test.shape)
print(X.shape)
print(y.shape)

(702, 49)
(235, 49)
(937, 49)
(937,)


In [ ]:
#generating prediction on test data
ypred = ada_boost.predict(X)

In [ ]:
import joblib

In [ ]:
# Save the best model
joblib.dump(ada_boost, "ada_boost.pkl")


['ada_boost.pkl']

In [ ]:
import random

In [ ]:
#  Create a new df with 20 random data points from the oil spill df
oil_spill_data = oil_spill_dataset[oil_spill_dataset["target"] == 1]
random_data = oil_spill_dataset.sample(n=20, random_state=40)
print(random_data.columns)

Index(['f_1', 'f_2', 'f_3', 'f_4', 'f_5', 'f_6', 'f_7', 'f_8', 'f_9', 'f_10',
       'f_11', 'f_12', 'f_13', 'f_14', 'f_15', 'f_16', 'f_17', 'f_18', 'f_19',
       'f_20', 'f_21', 'f_22', 'f_23', 'f_24', 'f_25', 'f_26', 'f_27', 'f_28',
       'f_29', 'f_30', 'f_31', 'f_32', 'f_33', 'f_34', 'f_35', 'f_36', 'f_37',
       'f_38', 'f_39', 'f_40', 'f_41', 'f_42', 'f_43', 'f_44', 'f_45', 'f_46',
       'f_47', 'f_48', 'f_49', 'target'],
      dtype='object')


In [ ]:
# Apply the saved model to predict the target column for the new df
new_dataset = random_data.drop("target", axis=1)

In [ ]:
new_dataset.to_csv('sample.csv')

In [ ]:
sample_data = pd.read_csv("sample.csv")
sample_data.shape

(20, 50)

In [ ]:
sample_data.head()

Unnamed: 0  f_1  f_2      f_3      f_4  f_5     f_6    f_7    f_8     f_9  \
0          85   75  109  1583.82  1301.25   48  272500  35.47  10.74  3600.0   
1         426  179   65  1527.91   886.32   90  162500  42.45  11.09  2100.0   
2         498    4  459    49.15   230.55   92  645468  27.07  14.57  6797.0   
3         918  186   10    74.00    21.20   64   81000  55.00   6.98   794.0   
4         768   36   19    49.05   399.26   64  153900  54.79   8.52  1805.0   

   ...  f_40     f_41    f_42    f_43    f_44   f_45  f_46      f_47   f_48  \
0  ...    55   921.95  672.68  313.73  186.47   2.94     0   3642.72  66.19   
1  ...    63   200.00  250.00  225.00   28.87   0.89     0   7469.27  65.94   
2  ...    86  2101.34  412.50  222.99   87.70   9.42     1  16373.66  35.96   
3  ...    50   402.49  180.00   90.00   73.48   4.47     0  13154.56  65.39   
4  ...    50   886.40   90.00   70.00   39.69  12.66     1   2525.72  65.88   

    f_49  
0   7.84  
1   7.84  
2  15.35  
3   6.68  
4   6.22  

[5 rows x 50 columns]

In [ ]:
sample_data.columns

Index(['Unnamed: 0', 'f_1', 'f_2', 'f_3', 'f_4', 'f_5', 'f_6', 'f_7', 'f_8',
       'f_9', 'f_10', 'f_11', 'f_12', 'f_13', 'f_14', 'f_15', 'f_16', 'f_17',
       'f_18', 'f_19', 'f_20', 'f_21', 'f_22', 'f_23', 'f_24', 'f_25', 'f_26',
       'f_27', 'f_28', 'f_29', 'f_30', 'f_31', 'f_32', 'f_33', 'f_34', 'f_35',
       'f_36', 'f_37', 'f_38', 'f_39', 'f_40', 'f_41', 'f_42', 'f_43', 'f_44',
       'f_45', 'f_46', 'f_47', 'f_48', 'f_49'],
      dtype='object')

In [ ]:
sample_data= sample_data.drop("Unnamed: 0", axis=1)

In [ ]:
# Load the saved model
loaded_model = joblib.load("ada_boost.pkl")

In [ ]:
# Apply the saved model to predict the target column for the new df
predictions_new_data = loaded_model.predict(sample_data)
print(predictions_new_data)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
# Apply the saved model to predict the target column for the new df
predictions_new_data = loaded_model.predict(sample_data)
print(predictions_new_data)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
